Include some extra info in help command mentioning the ability to use 'rtg RTG_MEM=NNg <subcommand>' style invocation, and improve bash completion.

diff --git a/installer/rtg b/installer/rtg
--- a/installer/rtg
+++ b/installer/rtg
@@ -27,6 +27,10 @@ while [ "${1:0:4}" == "RTG_" ]; do
         RTG_MEM=${1:8}
     elif [ "${1:0:14}" == "RTG_JAVA_OPTS=" ]; then
         RTG_JAVA_OPTS=${1:14}
+    else
+        echo "Error: expected RTG_MEM=NNg or RTG_JAVA_OPTS=\"<jvm arguments>\", e.g.:"
+        echo "    $0 RTG_MEM=16g help"
+        exit 1
     fi
     shift
 done
